lge: ruby
cache: bundler

rvm:
    - 2.1.2

script: 'CODECLIMATE_REPO_TOKEN=85a4bf6c462720b53a31ea40d510834bb603149c27b5c1759cc9d91b73963048  bundle exec rake'

notifications:
    email:
          recipients:
                  - sergeg1990@gmail.com
    on_failure: change
    on_success: neveranguage: ruby
